version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - UPLOAD_DIR=/app/uploads 